PREFIX ids:    <https://w3id.org/idsa/core/>
PREFIX void:   <http://rdfs.org/ns/void#>

SELECT DISTINCT ?resource ?x WHERE {
    ?resource a ids:DataResource ;
      void:vocabulary <http://www.w3.org/2000/01/rdf-schema#> .
}
