PREFIX ids:    <https://w3id.org/idsa/core/>
PREFIX void:   <http://rdfs.org/ns/void#>

SELECT DISTINCT ?resource ?x WHERE {
    ?resource a ids:DataResource ;
      void:vocabulary <https://w3id.org/idsa/core/> .
}
