PREFIX ids:                <https://w3id.org/idsa/core/>
PREFIX sh:                 <http://www.w3.org/ns/shacl#>

SELECT DISTINCT ?resource WHERE {
    ?resource a ids:DataResource ;
        sh:shapesGraph ?shape .

    ?shape sh:property ?property .

    ?property sh:path <https://statswales.gov.wales/Catalogue/Health-and-Social-Care/Life-Expectancy/lifeExpectancy> ;
        sh:minCount 1 ;
        sh:maxCount 1 ;
}
