# Name-spaces & prefixes:
# DCAT
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dctype: <http://purl.org/dc/dcmitype/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix dct: <http://purl.org/dc/terms/>
prefix vann: <http://purl.org/vocab/vann/>
prefix voaf: <http://purl.org/vocommons/voaf#>
prefix v: <http://www.w3.org/2006/vcard/ns#>
prefix schema: <http://schema.org/>

# DC elements
prefix dcam: <http://purl.org/dc/dcam/> 
prefix dcterms: <http://purl.org/dc/terms/> 

# ODRL
prefix odrl: <http://www.w3.org/ns/odrl/2/> 
prefix dct: <http://purl.org/dc/terms/> 
prefix vcard: <http://www.w3.org/2006/vcard/ns#> 
prefix cc: <http://creativecommons.org/ns#>

# Data Cube
prefix scovo:          <http://purl.org/NET/scovo#> 
prefix void:           <http://rdfs.org/ns/void#> 
prefix qb:             <http://purl.org/linked-data/cube#>

# ADMS
prefix xhv: <http://www.w3.org/1999/xhtml/vocab#>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix wdrs: <http://www.w3.org/2007/05/powder-s#>
prefix adms: <http://www.w3.org/ns/adms#>

# Prov
prefix prov: <http://www.w3.org/ns/prov#> 

# Org
prefix gr:         <http://purl.org/goodrelations/v1#> 
prefix owlTime:    <http://www.w3.org/2006/time#> 
prefix org:        <http://www.w3.org/ns/org#> 

# IDS
prefix ids: <https://w3id.org/ids/core/> 

# Selects nodes without annotation (orphaned objects)
SELECT distinct ?o
FROM <test.ttl> 
WHERE {
 ?s ?p ?o .
 OPTIONAL { ?o ?pp ?oo }
 FILTER (isIri(?o) && ! bound(?oo))
}



#SELECT distinct ?s
#WHERE {
#    ?onto owl:imports ?subonto .
#    GRAPH ?subonto { ?s ?p ?o }.
#}


#SELECT ?subonto
#WHERE {
#    GRAPH ?subonto { ?s ?p ?o } 
#    {
#       SELECT distinct ?subonto WHERE { ?onto owl:imports ?subonto }
#    }
#}


