#!/bin/bash
# Provides simply sanity check of the graph, e.g. testing for undefined resources (property ranges etc.)
# Depends on the `roqet` CLI utility provided by the Rasqal RDF library: http://librdf.org/rasqal/
# Install e.g. via "sudo apt install rasqal-utils"
# Usage: validate_graph ./InformationModel
echo "Not supported at moment"
