#!/bin/bash
# Depends on Redland Raptor RDF library: http://librdf.org/raptor/
# Install e.g. via "sudo apt-get install raptor2-utils"
# Usage: validate_tts ./InformationModel
cnt=0
err_cnt=0
if [ -d "$1" ]
    then
        echo "Validation of \"$1\" started"
        for f in `find $1  -name "*.ttl"`
        do
            cnt=$((cnt+1))
            # Parse silently omitting processing (-q) and default (--count) output
            # Redirect STDERR to STDOUT allowing to grep for error messages
            err=`rapper -q -i turtle $f --count 2>&1| grep -i err`
            if [ -n "$err" ]; then err_cnt=$((err_cnt+1)); echo "$f -> \"$err\""; fi
        done
        echo "Validation of $cnt file(s) completed with $err_cnt error(s)"
    else
        echo "Directory argument missing"
fi

